

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing Balance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BalanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Balance
        //private Balance instance;

        public BalanceTests()
        {
            // TODO uncomment below to create an instance of Balance
            //instance = new Balance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Balance
        /// </summary>
        [Fact]
        public void BalanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Balance
            //Assert.IsType<Balance>(instance);
        }


        /// <summary>
        /// Test the property 'GrossBalance'
        /// </summary>
        [Fact]
        public void GrossBalanceTest()
        {
            // TODO unit test for the property 'GrossBalance'
        }
        /// <summary>
        /// Test the property '_Balance'
        /// </summary>
        [Fact]
        public void _BalanceTest()
        {
            // TODO unit test for the property '_Balance'
        }
        /// <summary>
        /// Test the property 'AvailableBalance'
        /// </summary>
        [Fact]
        public void AvailableBalanceTest()
        {
            // TODO unit test for the property 'AvailableBalance'
        }
        /// <summary>
        /// Test the property 'Reserved'
        /// </summary>
        [Fact]
        public void ReservedTest()
        {
            // TODO unit test for the property 'Reserved'
        }
        /// <summary>
        /// Test the property 'PendingOutgoing'
        /// </summary>
        [Fact]
        public void PendingOutgoingTest()
        {
            // TODO unit test for the property 'PendingOutgoing'
        }
        /// <summary>
        /// Test the property 'FeeSell'
        /// </summary>
        [Fact]
        public void FeeSellTest()
        {
            // TODO unit test for the property 'FeeSell'
        }

    }

}
