

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing BankAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BankAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BankAccount
        //private BankAccount instance;

        public BankAccountTests()
        {
            // TODO uncomment below to create an instance of BankAccount
            //instance = new BankAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BankAccount
        /// </summary>
        [Fact]
        public void BankAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" BankAccount
            //Assert.IsType<BankAccount>(instance);
        }


        /// <summary>
        /// Test the property '_BankAccount'
        /// </summary>
        [Fact]
        public void _BankAccountTest()
        {
            // TODO unit test for the property '_BankAccount'
        }
        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Fact]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }

    }

}
