

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing BillingTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillingTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BillingTemplate
        //private BillingTemplate instance;

        public BillingTemplateTests()
        {
            // TODO uncomment below to create an instance of BillingTemplate
            //instance = new BillingTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BillingTemplate
        /// </summary>
        [Fact]
        public void BillingTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsType" BillingTemplate
            //Assert.IsType<BillingTemplate>(instance);
        }


        /// <summary>
        /// Test the property 'Purchase'
        /// </summary>
        [Fact]
        public void PurchaseTest()
        {
            // TODO unit test for the property 'Purchase'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Fact]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'IsTest'
        /// </summary>
        [Fact]
        public void IsTestTest()
        {
            // TODO unit test for the property 'IsTest'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'BrandId'
        /// </summary>
        [Fact]
        public void BrandIdTest()
        {
            // TODO unit test for the property 'BrandId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'IsSubscription'
        /// </summary>
        [Fact]
        public void IsSubscriptionTest()
        {
            // TODO unit test for the property 'IsSubscription'
        }
        /// <summary>
        /// Test the property 'InvoiceIssued'
        /// </summary>
        [Fact]
        public void InvoiceIssuedTest()
        {
            // TODO unit test for the property 'InvoiceIssued'
        }
        /// <summary>
        /// Test the property 'InvoiceDue'
        /// </summary>
        [Fact]
        public void InvoiceDueTest()
        {
            // TODO unit test for the property 'InvoiceDue'
        }
        /// <summary>
        /// Test the property 'InvoiceSkipCapture'
        /// </summary>
        [Fact]
        public void InvoiceSkipCaptureTest()
        {
            // TODO unit test for the property 'InvoiceSkipCapture'
        }
        /// <summary>
        /// Test the property 'InvoiceSendReceipt'
        /// </summary>
        [Fact]
        public void InvoiceSendReceiptTest()
        {
            // TODO unit test for the property 'InvoiceSendReceipt'
        }
        /// <summary>
        /// Test the property 'SubscriptionPeriod'
        /// </summary>
        [Fact]
        public void SubscriptionPeriodTest()
        {
            // TODO unit test for the property 'SubscriptionPeriod'
        }
        /// <summary>
        /// Test the property 'SubscriptionPeriodUnits'
        /// </summary>
        [Fact]
        public void SubscriptionPeriodUnitsTest()
        {
            // TODO unit test for the property 'SubscriptionPeriodUnits'
        }
        /// <summary>
        /// Test the property 'SubscriptionDuePeriod'
        /// </summary>
        [Fact]
        public void SubscriptionDuePeriodTest()
        {
            // TODO unit test for the property 'SubscriptionDuePeriod'
        }
        /// <summary>
        /// Test the property 'SubscriptionDuePeriodUnits'
        /// </summary>
        [Fact]
        public void SubscriptionDuePeriodUnitsTest()
        {
            // TODO unit test for the property 'SubscriptionDuePeriodUnits'
        }
        /// <summary>
        /// Test the property 'SubscriptionChargePeriodEnd'
        /// </summary>
        [Fact]
        public void SubscriptionChargePeriodEndTest()
        {
            // TODO unit test for the property 'SubscriptionChargePeriodEnd'
        }
        /// <summary>
        /// Test the property 'SubscriptionTrialPeriods'
        /// </summary>
        [Fact]
        public void SubscriptionTrialPeriodsTest()
        {
            // TODO unit test for the property 'SubscriptionTrialPeriods'
        }
        /// <summary>
        /// Test the property 'SubscriptionActive'
        /// </summary>
        [Fact]
        public void SubscriptionActiveTest()
        {
            // TODO unit test for the property 'SubscriptionActive'
        }
        /// <summary>
        /// Test the property 'SubscriptionHasActiveClients'
        /// </summary>
        [Fact]
        public void SubscriptionHasActiveClientsTest()
        {
            // TODO unit test for the property 'SubscriptionHasActiveClients'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Fact]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
