

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing BillingTemplateClient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillingTemplateClientTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BillingTemplateClient
        //private BillingTemplateClient instance;

        public BillingTemplateClientTests()
        {
            // TODO uncomment below to create an instance of BillingTemplateClient
            //instance = new BillingTemplateClient();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BillingTemplateClient
        /// </summary>
        [Fact]
        public void BillingTemplateClientInstanceTest()
        {
            // TODO uncomment below to test "IsType" BillingTemplateClient
            //Assert.IsType<BillingTemplateClient>(instance);
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SubscriptionBillingScheduledOn'
        /// </summary>
        [Fact]
        public void SubscriptionBillingScheduledOnTest()
        {
            // TODO unit test for the property 'SubscriptionBillingScheduledOn'
        }
        /// <summary>
        /// Test the property 'PaymentMethodWhitelist'
        /// </summary>
        [Fact]
        public void PaymentMethodWhitelistTest()
        {
            // TODO unit test for the property 'PaymentMethodWhitelist'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Fact]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
