

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing ClientDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientDetails
        //private ClientDetails instance;

        public ClientDetailsTests()
        {
            // TODO uncomment below to create an instance of ClientDetails
            //instance = new ClientDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientDetails
        /// </summary>
        [Fact]
        public void ClientDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientDetails
            //Assert.IsType<ClientDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'PersonalCode'
        /// </summary>
        [Fact]
        public void PersonalCodeTest()
        {
            // TODO unit test for the property 'PersonalCode'
        }
        /// <summary>
        /// Test the property 'StreetAddress'
        /// </summary>
        [Fact]
        public void StreetAddressTest()
        {
            // TODO unit test for the property 'StreetAddress'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'ZipCode'
        /// </summary>
        [Fact]
        public void ZipCodeTest()
        {
            // TODO unit test for the property 'ZipCode'
        }
        /// <summary>
        /// Test the property 'ShippingStreetAddress'
        /// </summary>
        [Fact]
        public void ShippingStreetAddressTest()
        {
            // TODO unit test for the property 'ShippingStreetAddress'
        }
        /// <summary>
        /// Test the property 'ShippingCountry'
        /// </summary>
        [Fact]
        public void ShippingCountryTest()
        {
            // TODO unit test for the property 'ShippingCountry'
        }
        /// <summary>
        /// Test the property 'ShippingCity'
        /// </summary>
        [Fact]
        public void ShippingCityTest()
        {
            // TODO unit test for the property 'ShippingCity'
        }
        /// <summary>
        /// Test the property 'ShippingZipCode'
        /// </summary>
        [Fact]
        public void ShippingZipCodeTest()
        {
            // TODO unit test for the property 'ShippingZipCode'
        }
        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Fact]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }
        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Fact]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }
        /// <summary>
        /// Test the property 'LegalName'
        /// </summary>
        [Fact]
        public void LegalNameTest()
        {
            // TODO unit test for the property 'LegalName'
        }
        /// <summary>
        /// Test the property 'BrandName'
        /// </summary>
        [Fact]
        public void BrandNameTest()
        {
            // TODO unit test for the property 'BrandName'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Fact]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }
        /// <summary>
        /// Test the property 'TaxNumber'
        /// </summary>
        [Fact]
        public void TaxNumberTest()
        {
            // TODO unit test for the property 'TaxNumber'
        }
        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Fact]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }
        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Fact]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }

    }

}
