

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing ClientRecurringTokenAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientRecurringTokenAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientRecurringTokenAllOf
        //private ClientRecurringTokenAllOf instance;

        public ClientRecurringTokenAllOfTests()
        {
            // TODO uncomment below to create an instance of ClientRecurringTokenAllOf
            //instance = new ClientRecurringTokenAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientRecurringTokenAllOf
        /// </summary>
        [Fact]
        public void ClientRecurringTokenAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientRecurringTokenAllOf
            //Assert.IsType<ClientRecurringTokenAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
