

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing FeeSell
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeeSellTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeeSell
        //private FeeSell instance;

        public FeeSellTests()
        {
            // TODO uncomment below to create an instance of FeeSell
            //instance = new FeeSell();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeeSell
        /// </summary>
        [Fact]
        public void FeeSellInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeeSell
            //Assert.IsType<FeeSell>(instance);
        }



    }

}
