

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse200
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse200Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse200
        //private InlineResponse200 instance;

        public InlineResponse200Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse200
            //instance = new InlineResponse200();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse200
        /// </summary>
        [Fact]
        public void InlineResponse200InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse200
            //Assert.IsType<InlineResponse200>(instance);
        }


        /// <summary>
        /// Test the property 'AvailablePaymentMethods'
        /// </summary>
        [Fact]
        public void AvailablePaymentMethodsTest()
        {
            // TODO unit test for the property 'AvailablePaymentMethods'
        }
        /// <summary>
        /// Test the property 'ByCountry'
        /// </summary>
        [Fact]
        public void ByCountryTest()
        {
            // TODO unit test for the property 'ByCountry'
        }
        /// <summary>
        /// Test the property 'CountryNames'
        /// </summary>
        [Fact]
        public void CountryNamesTest()
        {
            // TODO unit test for the property 'CountryNames'
        }
        /// <summary>
        /// Test the property 'Names'
        /// </summary>
        [Fact]
        public void NamesTest()
        {
            // TODO unit test for the property 'Names'
        }
        /// <summary>
        /// Test the property 'Logos'
        /// </summary>
        [Fact]
        public void LogosTest()
        {
            // TODO unit test for the property 'Logos'
        }
        /// <summary>
        /// Test the property 'CardMethods'
        /// </summary>
        [Fact]
        public void CardMethodsTest()
        {
            // TODO unit test for the property 'CardMethods'
        }

    }

}
