

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing InlineResponse2004
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2004Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004
        //private InlineResponse2004 instance;

        public InlineResponse2004Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2004
            //instance = new InlineResponse2004();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2004
        /// </summary>
        [Fact]
        public void InlineResponse2004InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineResponse2004
            //Assert.IsType<InlineResponse2004>(instance);
        }


        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }
        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Fact]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }

    }

}
