

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing IssuerDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssuerDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssuerDetails
        //private IssuerDetails instance;

        public IssuerDetailsTests()
        {
            // TODO uncomment below to create an instance of IssuerDetails
            //instance = new IssuerDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssuerDetails
        /// </summary>
        [Fact]
        public void IssuerDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssuerDetails
            //Assert.IsType<IssuerDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
        /// <summary>
        /// Test the property 'LegalStreetAddress'
        /// </summary>
        [Fact]
        public void LegalStreetAddressTest()
        {
            // TODO unit test for the property 'LegalStreetAddress'
        }
        /// <summary>
        /// Test the property 'LegalCountry'
        /// </summary>
        [Fact]
        public void LegalCountryTest()
        {
            // TODO unit test for the property 'LegalCountry'
        }
        /// <summary>
        /// Test the property 'LegalCity'
        /// </summary>
        [Fact]
        public void LegalCityTest()
        {
            // TODO unit test for the property 'LegalCity'
        }
        /// <summary>
        /// Test the property 'LegalZipCode'
        /// </summary>
        [Fact]
        public void LegalZipCodeTest()
        {
            // TODO unit test for the property 'LegalZipCode'
        }
        /// <summary>
        /// Test the property 'BankAccounts'
        /// </summary>
        [Fact]
        public void BankAccountsTest()
        {
            // TODO unit test for the property 'BankAccounts'
        }
        /// <summary>
        /// Test the property 'LegalName'
        /// </summary>
        [Fact]
        public void LegalNameTest()
        {
            // TODO unit test for the property 'LegalName'
        }
        /// <summary>
        /// Test the property 'BrandName'
        /// </summary>
        [Fact]
        public void BrandNameTest()
        {
            // TODO unit test for the property 'BrandName'
        }
        /// <summary>
        /// Test the property 'RegistrationNumber'
        /// </summary>
        [Fact]
        public void RegistrationNumberTest()
        {
            // TODO unit test for the property 'RegistrationNumber'
        }
        /// <summary>
        /// Test the property 'TaxNumber'
        /// </summary>
        [Fact]
        public void TaxNumberTest()
        {
            // TODO unit test for the property 'TaxNumber'
        }

    }

}
