

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentMethod
        //private PaymentMethod instance;

        public PaymentMethodTests()
        {
            // TODO uncomment below to create an instance of PaymentMethod
            //instance = new PaymentMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentMethod
        /// </summary>
        [Fact]
        public void PaymentMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentMethod
            //Assert.IsType<PaymentMethod>(instance);
        }



    }

}
