

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing Payment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Payment
        //private Payment instance;

        public PaymentTests()
        {
            // TODO uncomment below to create an instance of Payment
            //instance = new Payment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Payment
        /// </summary>
        [Fact]
        public void PaymentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Payment
            //Assert.IsType<Payment>(instance);
        }


        /// <summary>
        /// Test the property '_Client'
        /// </summary>
        [Fact]
        public void _ClientTest()
        {
            // TODO unit test for the property '_Client'
        }
        /// <summary>
        /// Test the property '_Payment'
        /// </summary>
        [Fact]
        public void _PaymentTest()
        {
            // TODO unit test for the property '_Payment'
        }
        /// <summary>
        /// Test the property 'TransactionData'
        /// </summary>
        [Fact]
        public void TransactionDataTest()
        {
            // TODO unit test for the property 'TransactionData'
        }
        /// <summary>
        /// Test the property 'RelatedTo'
        /// </summary>
        [Fact]
        public void RelatedToTest()
        {
            // TODO unit test for the property 'RelatedTo'
        }
        /// <summary>
        /// Test the property 'ReferenceGenerated'
        /// </summary>
        [Fact]
        public void ReferenceGeneratedTest()
        {
            // TODO unit test for the property 'ReferenceGenerated'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Fact]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'IsTest'
        /// </summary>
        [Fact]
        public void IsTestTest()
        {
            // TODO unit test for the property 'IsTest'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'BrandId'
        /// </summary>
        [Fact]
        public void BrandIdTest()
        {
            // TODO unit test for the property 'BrandId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Fact]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
