

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentDetails
        //private PaymentDetails instance;

        public PaymentDetailsTests()
        {
            // TODO uncomment below to create an instance of PaymentDetails
            //instance = new PaymentDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentDetails
        /// </summary>
        [Fact]
        public void PaymentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentDetails
            //Assert.IsType<PaymentDetails>(instance);
        }


        /// <summary>
        /// Test the property 'IsOutgoing'
        /// </summary>
        [Fact]
        public void IsOutgoingTest()
        {
            // TODO unit test for the property 'IsOutgoing'
        }
        /// <summary>
        /// Test the property 'PaymentType'
        /// </summary>
        [Fact]
        public void PaymentTypeTest()
        {
            // TODO unit test for the property 'PaymentType'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'NetAmount'
        /// </summary>
        [Fact]
        public void NetAmountTest()
        {
            // TODO unit test for the property 'NetAmount'
        }
        /// <summary>
        /// Test the property 'FeeAmount'
        /// </summary>
        [Fact]
        public void FeeAmountTest()
        {
            // TODO unit test for the property 'FeeAmount'
        }
        /// <summary>
        /// Test the property 'PendingAmount'
        /// </summary>
        [Fact]
        public void PendingAmountTest()
        {
            // TODO unit test for the property 'PendingAmount'
        }
        /// <summary>
        /// Test the property 'PendingUnfreezeOn'
        /// </summary>
        [Fact]
        public void PendingUnfreezeOnTest()
        {
            // TODO unit test for the property 'PendingUnfreezeOn'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PaidOn'
        /// </summary>
        [Fact]
        public void PaidOnTest()
        {
            // TODO unit test for the property 'PaidOn'
        }
        /// <summary>
        /// Test the property 'RemotePaidOn'
        /// </summary>
        [Fact]
        public void RemotePaidOnTest()
        {
            // TODO unit test for the property 'RemotePaidOn'
        }

    }

}
