

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing Payout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayoutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Payout
        //private Payout instance;

        public PayoutTests()
        {
            // TODO uncomment below to create an instance of Payout
            //instance = new Payout();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Payout
        /// </summary>
        [Fact]
        public void PayoutInstanceTest()
        {
            // TODO uncomment below to test "IsType" Payout
            //Assert.IsType<Payout>(instance);
        }


        /// <summary>
        /// Test the property 'Payment'
        /// </summary>
        [Fact]
        public void PaymentTest()
        {
            // TODO unit test for the property 'Payment'
        }
        /// <summary>
        /// Test the property '_Client'
        /// </summary>
        [Fact]
        public void _ClientTest()
        {
            // TODO unit test for the property '_Client'
        }
        /// <summary>
        /// Test the property 'TransactionData'
        /// </summary>
        [Fact]
        public void TransactionDataTest()
        {
            // TODO unit test for the property 'TransactionData'
        }
        /// <summary>
        /// Test the property 'ReferenceGenerated'
        /// </summary>
        [Fact]
        public void ReferenceGeneratedTest()
        {
            // TODO unit test for the property 'ReferenceGenerated'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusHistory'
        /// </summary>
        [Fact]
        public void StatusHistoryTest()
        {
            // TODO unit test for the property 'StatusHistory'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Fact]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'RecipientCardCountry'
        /// </summary>
        [Fact]
        public void RecipientCardCountryTest()
        {
            // TODO unit test for the property 'RecipientCardCountry'
        }
        /// <summary>
        /// Test the property 'RecipientCardBrand'
        /// </summary>
        [Fact]
        public void RecipientCardBrandTest()
        {
            // TODO unit test for the property 'RecipientCardBrand'
        }
        /// <summary>
        /// Test the property 'ExecutionUrl'
        /// </summary>
        [Fact]
        public void ExecutionUrlTest()
        {
            // TODO unit test for the property 'ExecutionUrl'
        }
        /// <summary>
        /// Test the property 'BrandId'
        /// </summary>
        [Fact]
        public void BrandIdTest()
        {
            // TODO unit test for the property 'BrandId'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Fact]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'IsTest'
        /// </summary>
        [Fact]
        public void IsTestTest()
        {
            // TODO unit test for the property 'IsTest'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Fact]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
