

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing PeriodUnits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PeriodUnitsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PeriodUnits
        //private PeriodUnits instance;

        public PeriodUnitsTests()
        {
            // TODO uncomment below to create an instance of PeriodUnits
            //instance = new PeriodUnits();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PeriodUnits
        /// </summary>
        [Fact]
        public void PeriodUnitsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PeriodUnits
            //Assert.IsType<PeriodUnits>(instance);
        }



    }

}
