

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseStatus
        //private PurchaseStatus instance;

        public PurchaseStatusTests()
        {
            // TODO uncomment below to create an instance of PurchaseStatus
            //instance = new PurchaseStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseStatus
        /// </summary>
        [Fact]
        public void PurchaseStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseStatus
            //Assert.IsType<PurchaseStatus>(instance);
        }



    }

}
