

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseDetails
        //private PurchaseDetails instance;

        public PurchaseDetailsTests()
        {
            // TODO uncomment below to create an instance of PurchaseDetails
            //instance = new PurchaseDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseDetails
        /// </summary>
        [Fact]
        public void PurchaseDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseDetails
            //Assert.IsType<PurchaseDetails>(instance);
        }


        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'Debt'
        /// </summary>
        [Fact]
        public void DebtTest()
        {
            // TODO unit test for the property 'Debt'
        }
        /// <summary>
        /// Test the property 'SubtotalOverride'
        /// </summary>
        [Fact]
        public void SubtotalOverrideTest()
        {
            // TODO unit test for the property 'SubtotalOverride'
        }
        /// <summary>
        /// Test the property 'TotalTaxOverride'
        /// </summary>
        [Fact]
        public void TotalTaxOverrideTest()
        {
            // TODO unit test for the property 'TotalTaxOverride'
        }
        /// <summary>
        /// Test the property 'TotalDiscountOverride'
        /// </summary>
        [Fact]
        public void TotalDiscountOverrideTest()
        {
            // TODO unit test for the property 'TotalDiscountOverride'
        }
        /// <summary>
        /// Test the property 'TotalOverride'
        /// </summary>
        [Fact]
        public void TotalOverrideTest()
        {
            // TODO unit test for the property 'TotalOverride'
        }
        /// <summary>
        /// Test the property 'RequestClientDetails'
        /// </summary>
        [Fact]
        public void RequestClientDetailsTest()
        {
            // TODO unit test for the property 'RequestClientDetails'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
        /// <summary>
        /// Test the property 'DueStrict'
        /// </summary>
        [Fact]
        public void DueStrictTest()
        {
            // TODO unit test for the property 'DueStrict'
        }
        /// <summary>
        /// Test the property 'EmailMessage'
        /// </summary>
        [Fact]
        public void EmailMessageTest()
        {
            // TODO unit test for the property 'EmailMessage'
        }

    }

}
