

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing Purchase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Purchase
        //private Purchase instance;

        public PurchaseTests()
        {
            // TODO uncomment below to create an instance of Purchase
            //instance = new Purchase();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Purchase
        /// </summary>
        [Fact]
        public void PurchaseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Purchase
            //Assert.IsType<Purchase>(instance);
        }


        /// <summary>
        /// Test the property '_Client'
        /// </summary>
        [Fact]
        public void _ClientTest()
        {
            // TODO unit test for the property '_Client'
        }
        /// <summary>
        /// Test the property '_Purchase'
        /// </summary>
        [Fact]
        public void _PurchaseTest()
        {
            // TODO unit test for the property '_Purchase'
        }
        /// <summary>
        /// Test the property 'Payment'
        /// </summary>
        [Fact]
        public void PaymentTest()
        {
            // TODO unit test for the property 'Payment'
        }
        /// <summary>
        /// Test the property 'IssuerDetails'
        /// </summary>
        [Fact]
        public void IssuerDetailsTest()
        {
            // TODO unit test for the property 'IssuerDetails'
        }
        /// <summary>
        /// Test the property 'TransactionData'
        /// </summary>
        [Fact]
        public void TransactionDataTest()
        {
            // TODO unit test for the property 'TransactionData'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusHistory'
        /// </summary>
        [Fact]
        public void StatusHistoryTest()
        {
            // TODO unit test for the property 'StatusHistory'
        }
        /// <summary>
        /// Test the property 'ViewedOn'
        /// </summary>
        [Fact]
        public void ViewedOnTest()
        {
            // TODO unit test for the property 'ViewedOn'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Fact]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'IsTest'
        /// </summary>
        [Fact]
        public void IsTestTest()
        {
            // TODO unit test for the property 'IsTest'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'BrandId'
        /// </summary>
        [Fact]
        public void BrandIdTest()
        {
            // TODO unit test for the property 'BrandId'
        }
        /// <summary>
        /// Test the property 'BillingTemplateId'
        /// </summary>
        [Fact]
        public void BillingTemplateIdTest()
        {
            // TODO unit test for the property 'BillingTemplateId'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'SendReceipt'
        /// </summary>
        [Fact]
        public void SendReceiptTest()
        {
            // TODO unit test for the property 'SendReceipt'
        }
        /// <summary>
        /// Test the property 'IsRecurringToken'
        /// </summary>
        [Fact]
        public void IsRecurringTokenTest()
        {
            // TODO unit test for the property 'IsRecurringToken'
        }
        /// <summary>
        /// Test the property 'RecurringToken'
        /// </summary>
        [Fact]
        public void RecurringTokenTest()
        {
            // TODO unit test for the property 'RecurringToken'
        }
        /// <summary>
        /// Test the property 'SkipCapture'
        /// </summary>
        [Fact]
        public void SkipCaptureTest()
        {
            // TODO unit test for the property 'SkipCapture'
        }
        /// <summary>
        /// Test the property 'ForceRecurring'
        /// </summary>
        [Fact]
        public void ForceRecurringTest()
        {
            // TODO unit test for the property 'ForceRecurring'
        }
        /// <summary>
        /// Test the property 'ReferenceGenerated'
        /// </summary>
        [Fact]
        public void ReferenceGeneratedTest()
        {
            // TODO unit test for the property 'ReferenceGenerated'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'Issued'
        /// </summary>
        [Fact]
        public void IssuedTest()
        {
            // TODO unit test for the property 'Issued'
        }
        /// <summary>
        /// Test the property 'Due'
        /// </summary>
        [Fact]
        public void DueTest()
        {
            // TODO unit test for the property 'Due'
        }
        /// <summary>
        /// Test the property 'RefundAvailability'
        /// </summary>
        [Fact]
        public void RefundAvailabilityTest()
        {
            // TODO unit test for the property 'RefundAvailability'
        }
        /// <summary>
        /// Test the property 'RefundableAmount'
        /// </summary>
        [Fact]
        public void RefundableAmountTest()
        {
            // TODO unit test for the property 'RefundableAmount'
        }
        /// <summary>
        /// Test the property 'CurrencyConversion'
        /// </summary>
        [Fact]
        public void CurrencyConversionTest()
        {
            // TODO unit test for the property 'CurrencyConversion'
        }
        /// <summary>
        /// Test the property 'PaymentMethodWhitelist'
        /// </summary>
        [Fact]
        public void PaymentMethodWhitelistTest()
        {
            // TODO unit test for the property 'PaymentMethodWhitelist'
        }
        /// <summary>
        /// Test the property 'SuccessRedirect'
        /// </summary>
        [Fact]
        public void SuccessRedirectTest()
        {
            // TODO unit test for the property 'SuccessRedirect'
        }
        /// <summary>
        /// Test the property 'FailureRedirect'
        /// </summary>
        [Fact]
        public void FailureRedirectTest()
        {
            // TODO unit test for the property 'FailureRedirect'
        }
        /// <summary>
        /// Test the property 'CancelRedirect'
        /// </summary>
        [Fact]
        public void CancelRedirectTest()
        {
            // TODO unit test for the property 'CancelRedirect'
        }
        /// <summary>
        /// Test the property 'SuccessCallback'
        /// </summary>
        [Fact]
        public void SuccessCallbackTest()
        {
            // TODO unit test for the property 'SuccessCallback'
        }
        /// <summary>
        /// Test the property 'CreatorAgent'
        /// </summary>
        [Fact]
        public void CreatorAgentTest()
        {
            // TODO unit test for the property 'CreatorAgent'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Fact]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }
        /// <summary>
        /// Test the property 'CreatedFromIp'
        /// </summary>
        [Fact]
        public void CreatedFromIpTest()
        {
            // TODO unit test for the property 'CreatedFromIp'
        }
        /// <summary>
        /// Test the property 'InvoiceUrl'
        /// </summary>
        [Fact]
        public void InvoiceUrlTest()
        {
            // TODO unit test for the property 'InvoiceUrl'
        }
        /// <summary>
        /// Test the property 'CheckoutUrl'
        /// </summary>
        [Fact]
        public void CheckoutUrlTest()
        {
            // TODO unit test for the property 'CheckoutUrl'
        }
        /// <summary>
        /// Test the property 'DirectPostUrl'
        /// </summary>
        [Fact]
        public void DirectPostUrlTest()
        {
            // TODO unit test for the property 'DirectPostUrl'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Fact]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
