

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionFlow
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionFlowTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionFlow
        //private TransactionFlow instance;

        public TransactionFlowTests()
        {
            // TODO uncomment below to create an instance of TransactionFlow
            //instance = new TransactionFlow();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionFlow
        /// </summary>
        [Fact]
        public void TransactionFlowInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionFlow
            //Assert.IsType<TransactionFlow>(instance);
        }



    }

}
