

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionProduct
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionProductTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionProduct
        //private TransactionProduct instance;

        public TransactionProductTests()
        {
            // TODO uncomment below to create an instance of TransactionProduct
            //instance = new TransactionProduct();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionProduct
        /// </summary>
        [Fact]
        public void TransactionProductInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionProduct
            //Assert.IsType<TransactionProduct>(instance);
        }



    }

}
