

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing Turnover
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TurnoverTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Turnover
        //private Turnover instance;

        public TurnoverTests()
        {
            // TODO uncomment below to create an instance of Turnover
            //instance = new Turnover();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Turnover
        /// </summary>
        [Fact]
        public void TurnoverInstanceTest()
        {
            // TODO uncomment below to test "IsType" Turnover
            //Assert.IsType<Turnover>(instance);
        }


        /// <summary>
        /// Test the property '_Turnover'
        /// </summary>
        [Fact]
        public void _TurnoverTest()
        {
            // TODO unit test for the property '_Turnover'
        }
        /// <summary>
        /// Test the property 'FeeSell'
        /// </summary>
        [Fact]
        public void FeeSellTest()
        {
            // TODO unit test for the property 'FeeSell'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

    }

}
