

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing TurnoverCount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TurnoverCountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TurnoverCount
        //private TurnoverCount instance;

        public TurnoverCountTests()
        {
            // TODO uncomment below to create an instance of TurnoverCount
            //instance = new TurnoverCount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TurnoverCount
        /// </summary>
        [Fact]
        public void TurnoverCountInstanceTest()
        {
            // TODO uncomment below to test "IsType" TurnoverCount
            //Assert.IsType<TurnoverCount>(instance);
        }


        /// <summary>
        /// Test the property 'All'
        /// </summary>
        [Fact]
        public void AllTest()
        {
            // TODO unit test for the property 'All'
        }

    }

}
