

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing TurnoverPair
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TurnoverPairTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TurnoverPair
        //private TurnoverPair instance;

        public TurnoverPairTests()
        {
            // TODO uncomment below to create an instance of TurnoverPair
            //instance = new TurnoverPair();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TurnoverPair
        /// </summary>
        [Fact]
        public void TurnoverPairInstanceTest()
        {
            // TODO uncomment below to test "IsType" TurnoverPair
            //Assert.IsType<TurnoverPair>(instance);
        }


        /// <summary>
        /// Test the property 'Incoming'
        /// </summary>
        [Fact]
        public void IncomingTest()
        {
            // TODO unit test for the property 'Incoming'
        }
        /// <summary>
        /// Test the property 'Outgoing'
        /// </summary>
        [Fact]
        public void OutgoingTest()
        {
            // TODO unit test for the property 'Outgoing'
        }

    }

}
