

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.Chip.Api;
using Org.Chip.Model;
using Org.Chip.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.Chip.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookAllOf
        //private WebhookAllOf instance;

        public WebhookAllOfTests()
        {
            // TODO uncomment below to create an instance of WebhookAllOf
            //instance = new WebhookAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookAllOf
        /// </summary>
        [Fact]
        public void WebhookAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookAllOf
            //Assert.IsType<WebhookAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'AllEvents'
        /// </summary>
        [Fact]
        public void AllEventsTest()
        {
            // TODO unit test for the property 'AllEvents'
        }
        /// <summary>
        /// Test the property 'PublicKey'
        /// </summary>
        [Fact]
        public void PublicKeyTest()
        {
            // TODO unit test for the property 'PublicKey'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'Callback'
        /// </summary>
        [Fact]
        public void CallbackTest()
        {
            // TODO unit test for the property 'Callback'
        }

    }

}
